version: '3.2'

services:
  client-souptor01:
    container_name: client-souptor01
    image: souptor:latest
    restart: unless-stopped
    networks:
      - souptor

  client-souptor02:
    container_name: client-souptor02
    image: souptor:latest
    restart: unless-stopped
    networks:
      - souptor

networks:
  souptor:
    external:
      name: souptor